included: 
  - Tests
  - ActionsDemo

reporter: "xcode"

disabled_rules:
  - function_parameter_count
  - function_body_length
  - type_body_length
  - force_try
  - force_cast
  - cyclomatic_complexity
  - identifier_name
  - type_name
  - line_length
  - file_length
  - large_tuple
  - nesting
  - unused_setter_value
