default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :test do
    run_tests(
      workspace: "ActionsDemo.xcworkspace",
      devices: ["iPhone 8"],
      scheme: "ActionsDemo"
    )
  end
end
