on: [push]
name: Unit Tests

jobs:
  test:
    name: Unit Tests
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master

    - name: Install Bundler & Gems
      run: |
        gem install bundler:1.17.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
 
    - name: Unit Tests
      env:
        # See also: https://help.github.com/en/articles/software-in-virtual-environments-for-github-actions#xcode
        XCODE_PATH: "/Applications/Xcode_11.3.app"
        DEVELOPER_DIR: "/Applications/Xcode_11.3.app/Contents/Developer"
      run: fastlane test
